---
name: Deploy Glue Infrastructure

"on":
  push:
    branches:
      - main

env:
  REGION: ${{ secrets.AWS_REGION }}
  BUCKET_NAME: ${{ secrets.GLUE_BUCKET }}
  AWS_WEB_ROLE: ${{ secrets.AWS_WEB_ROLE }}
  DEST_PATH: code/customer_analytics

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_WEB_ROLE }}
          aws-region: ${{ env.REGION }}

      - name: Create S3 Buckets if not exist
        run: |
          python infrastructure/create_s3_buckets.py $BUCKET_NAME $REGION

      - name: Create S3 folders if not exist
        run: |
          python infrastructure/create_folders.py $BUCKET_NAME \
          "analytics/" \
          "code/customer_analytics/" 

      - name: Build wheel file
        run: python setup.py bdist_wheel

      - name: Upload Wheel Artifact to S3
        run: |
          WHEEL_FILE=$(ls dist/ | grep -E "customer_analytics-.*\.whl" | head -n 1)
          echo "WHEEL_FILE=$WHEEL_FILE" >> $GITHUB_ENV
          aws s3 cp dist/$WHEEL_FILE s3://$BUCKET_NAME/$DEST_PATH/

      - name: Create Glue Crawlers
        run: |
          python infrastructure/create_glue_crawlers.py customer360_crawler \
          $AWS_WEB_ROLE customer_analytics \
          s3://$BUCKET_NAME/analytics/

      - name: Create Glue Workflow
        run: |
          python infrastructure/create_glue_workflows.py customer360_workflow

  deploy_glue_jobs:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        glue: [purchase_behavior, churn_prediction, omni_channel_engagement, fraud_detection, pricing_trends]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - run: |
          pip install -r requirements.txt
          pip install boto3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_WEB_ROLE }}
          aws-region: ${{ env.REGION }}

      - name: Create S3 folders if not exist
        run: |
          python infrastructure/create_folders.py $BUCKET_NAME \
          "code/temp/${{ matrix.glue }}/"

      - name: Upload Glue Script to S3
        run: |
          aws s3 cp glue_upload_script/${{ matrix.glue }}.py \
          s3://$BUCKET_NAME/$DEST_PATH/${{ matrix.glue }}.py

      - name: Deploy Glue Job - ${{ matrix.glue }}
        run: |
          python infrastructure/create_glue_jobs.py ${{ matrix.glue }} \
          $AWS_WEB_ROLE \
          s3://$BUCKET_NAME/$DEST_PATH/${{ matrix.glue }}.py \
          $BUCKET_NAME \
          s3://$BUCKET_NAME/$DEST_PATH/$WHEEL_FILE
