---
name: Deploy Glue Infrastructure

"on":
  push:
    branches:
      - main

env:
  REGION: ${{ secrets.AWS_REGION }}
  BUCKET_NAME: ${{ secrets.GLUE_BUCKET }}
  AWS_WEB_ROLE: ${{ secrets.AWS_WEB_ROLE }}
  DEST_PATH: code/customer_analytics
  AWS_CRAWLER_NAME: customer360_crawler
  AWS_WORKFLOW_NAME: customer360_workflow
  WHEEL_FILE_NAME: customer_analytics-0.1.0-py3-none-any.whl

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_WEB_ROLE }}
          aws-region: ${{ env.REGION }}

      - name: Create S3 Buckets if not exist
        run: |
          python infrastructure/create_s3_buckets.py $BUCKET_NAME $REGION

      - name: Create S3 folders if not exist
        run: |
          python infrastructure/create_folders.py $BUCKET_NAME \
          "analytics/" "code/customer_analytics/"

      - name: Build wheel file
        run: python setup.py bdist_wheel

      - name: Upload Wheel Artifact to S3
        run: |
          aws s3 cp dist/$WHEEL_FILE_NAME s3://$BUCKET_NAME/$DEST_PATH/

      - name: Create Glue Crawlers
        run: |
          python infrastructure/create_glue_crawlers.py $AWS_CRAWLER_NAME \
          $AWS_WEB_ROLE customer_analytics \
          s3://$BUCKET_NAME/analytics/

      - name: Create Glue Workflow
        run: |
          python infrastructure/create_glue_workflows.py $AWS_WORKFLOW_NAME

  deploy_glue_jobs:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        glue: ["purchase_behavior","churn_prediction","omni_channel_engagement","fraud_detection","pricing_trends"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install boto3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_WEB_ROLE }}
          aws-region: ${{ env.REGION }}

      - name: Create S3 folders if not exist
        run: |
          python infrastructure/create_folders.py $BUCKET_NAME \
          "code/temp/${{ matrix.glue }}/"

      - name: Upload Glue Script to S3
        run: |
          aws s3 cp glue_upload_script/${{ matrix.glue }}.py \
          s3://$BUCKET_NAME/$DEST_PATH/${{ matrix.glue }}.py

      - name: Deploy Glue Job - ${{ matrix.glue }}
        run: |
          python infrastructure/create_glue_jobs.py ${{ matrix.glue }} \
          $AWS_WEB_ROLE \
          s3://$BUCKET_NAME/$DEST_PATH/${{ matrix.glue }}.py \
          $BUCKET_NAME \
          s3://$BUCKET_NAME/$DEST_PATH/$WHEEL_FILE_NAME

  create_glue_triggers:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install boto3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_WEB_ROLE }}
          aws-region: ${{ env.REGION }}

      - name: Create Glue Triggers
        run: |
          python infrastructure/create_glue_triggers.py \
          '["purchase_behavior","churn_prediction","omni_channel_engagement","fraud_detection","pricing_trends"]' \
          $REGION $BUCKET_NAME $AWS_CRAWLER_NAME $AWS_WORKFLOW_NAME
