name: Deploy Glue Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        glue: [purchase_behavior, churn_prediction, omni_channel_engagement, fraud_detection, pricing_trends]

    env:
      REGION: ${{ secrets.AWS_REGION }}
      BUCKET_NAME: ${{ secrets.GLUE_BUCKET }}
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      IAM_ROLE_NAME: GlueDevRole
      AWS_WEB_ROLE: ${{ secrets.AWS_WEB_ROLE }}
      PROJECT_LIB_PATH: s3://$BUCKET_NAME/code/libs/

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_WEB_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create S3 Buckets if not exist
        run: |
          python infrastructure/create_s3_buckets.py ${{ secrets.GLUE_BUCKET }} ${{ secrets.AWS_REGION }}

      - name: Create S3 folders if not exist
        run: |
          python infrastructure/create_folders.py ${{ secrets.GLUE_BUCKET }} \
          "analytics/" \
          "code/customer_analytics/" \
          "code/temp/${{ matrix.glue }}/"

      - name: Create IAM Role for Glue Jobs
        run: |
          python infrastructure/iam_roles.py ${{ secrets.IAM_ROLE_NAME }}
      
      - name: Read IAM Role ARN
        id: read_role
        run: |
          echo "I_ROLE_ARN=$(cat iam_role_arn.txt)" >> "$GITHUB_ENV"

      - name: Create Glue Jobs
        run: |
          python infrastructure/create_glue_jobs.py churn_prediction $I_ROLE_ARN s3://$BUCKET_NAME/code/churn_prediction.py $BUCKET_NAME ${{ env.PROJECT_LIB_PATH }}
          python infrastructure/create_glue_jobs.py purchase_behavior $I_ROLE_ARN s3://$BUCKET_NAME/code/purchase_behavior.py $BUCKET_NAME ${{ env.PROJECT_LIB_PATH }}
          python infrastructure/create_glue_jobs.py omni_channel_engagement $I_ROLE_ARN s3://$BUCKET_NAME/code/omni_channel_engagement.py $BUCKET_NAME ${{ env.PROJECT_LIB_PATH }}
          python infrastructure/create_glue_jobs.py fraud_detection $I_ROLE_ARN s3://$BUCKET_NAME/code/fraud_detection.py $BUCKET_NAME ${{ env.PROJECT_LIB_PATH }}
          python infrastructure/create_glue_jobs.py pricing_trends $I_ROLE_ARN s3://$BUCKET_NAME/code/pricing_trends.py $BUCKET_NAME ${{ env.PROJECT_LIB_PATH }}

      - name: Create Glue Crawlers
        run: |
          python infrastructure/create_glue_crawlers.py customer360_crawler $I_ROLE_ARN customer_analytics s3://$BUCKET_NAME/analytics/

      - name: Create Glue Workflow
        run: |
          python infrastructure/create_glue_workflows.py customer360_workflow

